version: "2"

services:
  master:
    build: ./salt-master
    privileged: true
    restart: always
    container_name: "salt-master"
    hostname: "devops-salt-master"
    volumes:
     - ./salt/:/srv/salt
     - ./pillar/:/srv/pillar
    ports:
      - '22033:22'
    
    networks:
      - salt-stack-net

  minion1:
    build: ./salt-minion
    privileged: true
    restart: always
    container_name: "salt-minion-1"
    hostname: "salt-minion-1"
    ports:
      - '22034:22'

    networks:
      - salt-stack-net

  minion2:
    build: ./salt-minion
    privileged: true
    restart: always
    container_name: "salt-minion-2"
    hostname: "salt-minion-2"
    ports:
      - '22035:22'
    
    networks:
      - salt-stack-net

networks:
  salt-stack-net:
    driver: bridge
